import { Header } from '@/components/ui/MarketingSections';
import { createClient } from '@/utils/supabase/server';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function MarketingLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const supabase = createClient();

  const {
    data: { user }
  } = await supabase.auth.getUser();

  return (
    <div className={inter.className}>
      <Header user={user} />
      <main>{children}</main>
    </div>
  );
}
